// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jecdjblxkjqmtwdoyxkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY2RqYmx4a2pxbXR3ZG95eGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Nzc1MDYsImV4cCI6MjA1ODA1MzUwNn0.qhaWeP_coFuj6NQAZzWnKhCr7IONAu5eEa4HWk0InV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);